# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Argus < Formula
  desc "The command line tool for the Argus platform."
  homepage "https://github.com/chanzuckerberg/argus-artifacts"
  version "0.61.0"

  on_macos do
    on_intel do
      url "https://github.com/chanzuckerberg/argus-artifacts/releases/download/v0.61.0/argus_0.61.0_darwin_amd64.tar.gz"
      sha256 "ffcd3ff61800f3345d57387af4cb6a09cf85613ba26b7e84b0601bd62fe50a45"

      def install
        bin.install "argus"
      end
    end
    on_arm do
      url "https://github.com/chanzuckerberg/argus-artifacts/releases/download/v0.61.0/argus_0.61.0_darwin_arm64.tar.gz"
      sha256 "1049f76c2eb933dde642bb9a61beae7ac102423efe5f64e8f3cfcd18fde5b266"

      def install
        bin.install "argus"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chanzuckerberg/argus-artifacts/releases/download/v0.61.0/argus_0.61.0_linux_amd64.tar.gz"
        sha256 "7ce23a2fece4e57dccc5257646db397ad8f592f388a32808899539ac29d7ebb3"

        def install
          bin.install "argus"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chanzuckerberg/argus-artifacts/releases/download/v0.61.0/argus_0.61.0_linux_arm64.tar.gz"
        sha256 "d6786fdabcfa0e25922cf9b4eb28fba29bded5d07082aae1191e93940f82fbf9"

        def install
          bin.install "argus"
        end
      end
    end
  end

  test do
    system "#{bin}/argus version"
  end
end
