# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Argus < Formula
  desc "The command line tool for the Argus platform."
  homepage "https://github.com/chanzuckerberg/argus-artifacts"
  version "0.141.4"

  on_macos do
    on_intel do
      url "https://github.com/chanzuckerberg/argus-artifacts/releases/download/v0.141.4/argus_0.141.4_darwin_amd64.tar.gz"
      sha256 "fdab315190b914fbe3341c5cb974b185a7f2e586411021d32ff19e8f5a06bfeb"

      def install
        bin.install "argus"
      end
    end
    on_arm do
      url "https://github.com/chanzuckerberg/argus-artifacts/releases/download/v0.141.4/argus_0.141.4_darwin_arm64.tar.gz"
      sha256 "a0b3a94c0968b50fa43e3e9943399d74da90aab8a3d0bb299c744c5fc9478e31"

      def install
        bin.install "argus"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chanzuckerberg/argus-artifacts/releases/download/v0.141.4/argus_0.141.4_linux_amd64.tar.gz"
        sha256 "7a5cdf233affdc7754645270d8b0f07fca0620ae5cfc5eb021c4f9d2e970168e"

        def install
          bin.install "argus"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chanzuckerberg/argus-artifacts/releases/download/v0.141.4/argus_0.141.4_linux_arm64.tar.gz"
        sha256 "e1c2d506ebe9e744c1f4b028d67d8708168ef3c2e98de53129c1204ed69025e6"

        def install
          bin.install "argus"
        end
      end
    end
  end

  test do
    system "#{bin}/argus version"
  end
end
