# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsOidc < Formula
  desc "A command line utility tool to help generate AWS STS credentials from an OIDC application."
  homepage "https://github.com/chanzuckerberg/aws-oidc"
  version "0.28.13"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chanzuckerberg/aws-oidc/releases/download/v0.28.13/aws-oidc_0.28.13_darwin_arm64.tar.gz"
      sha256 "43a2729fcf5278e71ddd753e105d35da03f4a8696ee40c1e6ce1f71a22306d69"

      def install
        bin.install "aws-oidc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/aws-oidc/releases/download/v0.28.13/aws-oidc_0.28.13_darwin_amd64.tar.gz"
      sha256 "e0b118c657a1d8df04d2c090856a5b0c68c11833d6e76753b33137ca1137a55a"

      def install
        bin.install "aws-oidc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/aws-oidc/releases/download/v0.28.13/aws-oidc_0.28.13_linux_amd64.tar.gz"
      sha256 "02339c81464d4d607da139db7d064d1b1e8fc62a739692e02cada4b6fc02d803"

      def install
        bin.install "aws-oidc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chanzuckerberg/aws-oidc/releases/download/v0.28.13/aws-oidc_0.28.13_linux_arm64.tar.gz"
      sha256 "7ef408d382630c87ad967aeef8c506f925c3f4129e4018a9413a5f093ccf0b77"

      def install
        bin.install "aws-oidc"
      end
    end
  end

  test do
    system "#{bin}/aws-oidc version"
  end
end
