# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsOidc < Formula
  desc "A command line utility tool to help generate AWS STS credentials from an OIDC application."
  homepage "https://github.com/chanzuckerberg/aws-oidc"
  version "0.28.49"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chanzuckerberg/aws-oidc/releases/download/v0.28.49/aws-oidc_0.28.49_darwin_arm64.tar.gz"
      sha256 "65727524ede2077c68062503e62a415671d1ce7ddcf6adf710e6b05302b4a49f"

      def install
        bin.install "aws-oidc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/aws-oidc/releases/download/v0.28.49/aws-oidc_0.28.49_darwin_amd64.tar.gz"
      sha256 "c0cb464b9f3ad0505ee853bb9d4ac691972b162081862da10bc04330f4cc8102"

      def install
        bin.install "aws-oidc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chanzuckerberg/aws-oidc/releases/download/v0.28.49/aws-oidc_0.28.49_linux_arm64.tar.gz"
      sha256 "ab1aed4339b3617b45dfd529df8025975deee0377038b48d8711fdab7e3578a3"

      def install
        bin.install "aws-oidc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/aws-oidc/releases/download/v0.28.49/aws-oidc_0.28.49_linux_amd64.tar.gz"
      sha256 "67f5549d9f499e01b8283468c713f50440a62a8bd57edfb364f873bb01284d45"

      def install
        bin.install "aws-oidc"
      end
    end
  end

  test do
    system "#{bin}/aws-oidc version"
  end
end
