# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsOidcRc < Formula
  desc "A command line utility tool to help generate AWS STS credentials from an OIDC application."
  homepage "https://github.com/chanzuckerberg/aws-oidc"
  version "0.25.43-a43da5a"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chanzuckerberg/aws-oidc/releases/download/v0.25.43-a43da5a/aws-oidc_0.25.43-a43da5a_darwin_arm64.tar.gz"
      sha256 "163f4281a585dd7ed8039a11906d473cf0d7d7fd89229ba01226416dfb8f5d3f"

      def install
        bin.install "aws-oidc-rc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/aws-oidc/releases/download/v0.25.43-a43da5a/aws-oidc_0.25.43-a43da5a_darwin_amd64.tar.gz"
      sha256 "39c2788d8294e02e066f8a041d2d4c6d960e6125b4befcd0ec067e58445dfc69"

      def install
        bin.install "aws-oidc-rc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chanzuckerberg/aws-oidc/releases/download/v0.25.43-a43da5a/aws-oidc_0.25.43-a43da5a_linux_arm64.tar.gz"
      sha256 "1c4bb7d7afe36a6bbff79688ac600dc040ca78ba6b556eb3f7a8a85ba103cfb2"

      def install
        bin.install "aws-oidc-rc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/aws-oidc/releases/download/v0.25.43-a43da5a/aws-oidc_0.25.43-a43da5a_linux_amd64.tar.gz"
      sha256 "54667d5094efecb540e8663d9168883825cf603f229a88d4fed0bb1b6bd719cc"

      def install
        bin.install "aws-oidc-rc"
      end
    end
  end

  test do
    system "#{bin}/aws-oidc version"
  end
end
