# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsOidcRc < Formula
  desc "A command line utility tool to help generate AWS STS credentials from an OIDC application."
  homepage "https://github.com/chanzuckerberg/aws-oidc"
  version "0.25.62-51e2f37"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chanzuckerberg/aws-oidc/releases/download/v0.25.62-51e2f37/aws-oidc_0.25.62-51e2f37_darwin_arm64.tar.gz"
      sha256 "6ca1666aa420f7860987fd49f035a0cf3504452de19dca020aaf972654b04f89"

      def install
        bin.install "aws-oidc-rc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/aws-oidc/releases/download/v0.25.62-51e2f37/aws-oidc_0.25.62-51e2f37_darwin_amd64.tar.gz"
      sha256 "c16ed50e63370238e9d59f2b5e1ec836c132f251f5acb0a8ea7fe7b846bcabba"

      def install
        bin.install "aws-oidc-rc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/aws-oidc/releases/download/v0.25.62-51e2f37/aws-oidc_0.25.62-51e2f37_linux_amd64.tar.gz"
      sha256 "f732b88661da260a5ff4da4a2d4af29f5263ed5f1bd0fcf3da3309778d4a240a"

      def install
        bin.install "aws-oidc-rc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chanzuckerberg/aws-oidc/releases/download/v0.25.62-51e2f37/aws-oidc_0.25.62-51e2f37_linux_arm64.tar.gz"
      sha256 "c829d8a85795ea80be8896deac76ed68afdbc5b93f71edb2e9562fed3dad3dc1"

      def install
        bin.install "aws-oidc-rc"
      end
    end
  end

  test do
    system "#{bin}/aws-oidc version"
  end
end
