# This file was generated by GoReleaser. DO NOT EDIT.
class Bff < Formula
  desc "Breaking, Feature, Fix - a tool for managing semantic versioning"
  homepage "https://github.com/chanzuckerberg/bff"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/chanzuckerberg/bff/releases/download/v0.2.0/bff_0.2.0_darwin_amd64.tar.gz"
    sha256 "44e7d9eca69e9bb452557da4437cd753f436e54b2e4b6ccb011b700770807542"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/bff/releases/download/v0.2.0/bff_0.2.0_linux_amd64.tar.gz"
      sha256 "a9a5d5eff6401b7b188253d1df467e973f9714e63f580b3af35d2474e56f7cd1"
    end
  end

  def install
    bin.install "bff"
  end

  test do
    system "#{bin}/bff version"
  end
end
