# This file was generated by GoReleaser. DO NOT EDIT.
class Bff < Formula
  desc "Breaking, Feature, Fix - a tool for managing semantic versioning"
  homepage "https://github.com/chanzuckerberg/bff"
  version "0.1.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/chanzuckerberg/bff/releases/download/v0.1.6/bff_0.1.6_darwin_amd64.tar.gz"
    sha256 "09ad4e78809d1f23b62e49975dfd3dbcd6a44040ffac19d404403335389d9204"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/bff/releases/download/v0.1.6/bff_0.1.6_linux_amd64.tar.gz"
      sha256 "54b48e5ac62503aabcd575baba51fda2f2349ddaa611ad8a7381432387d35ce2"
    end
  end

  def install
    bin.install "bff"
  end

  test do
    system "#{bin}/bff version"
  end
end
