# This file was generated by GoReleaser. DO NOT EDIT.
class Blessclient < Formula
  desc "SSH without pain."
  homepage "https://github.com/chanzuckerberg/blessclient"
  version "0.4.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/chanzuckerberg/blessclient/releases/download/v0.4.9/blessclient_0.4.9_darwin_amd64.tar.gz"
    sha256 "a878f3e3f4cbf8daeda6c7294b9995229ce98ccd009048cc252fd40f7117f0d9"
  elsif OS.linux?
  end

  def install
    bin.install "blessclient"
  end

  test do
    system "#{bin}/blessclient version"
  end
end
