# This file was generated by GoReleaser. DO NOT EDIT.
class Blessclient < Formula
  desc "SSH without pain."
  homepage "https://github.com/chanzuckerberg/blessclient"
  url "https://github.com/chanzuckerberg/blessclient/releases/download/v0.4.6/blessclient_0.4.6_darwin_amd64.tar.gz"
  version "0.4.6"
  sha256 "1a09f84f61ab286f88e16542f161efacd85576bed2ef5ffe9625c88ecc5ce132"

  def install
    bin.install "blessclient"
  end

  test do
    system "#{bin}/blessclient version"
  end
end
