# This file was generated by GoReleaser. DO NOT EDIT.
class Blessclient@0 < Formula
  desc "SSH without pain."
  homepage "https://github.com/chanzuckerberg/blessclient"
  version "0.6.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/chanzuckerberg/blessclient/releases/download/v0.6.0/blessclient_0.6.0_darwin_amd64.tar.gz"
    sha256 "22f2a2404a781b90348768231a616dd3905c14fdc3e1961095413c23634b000b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/blessclient/releases/download/v0.6.0/blessclient_0.6.0_linux_amd64.tar.gz"
      sha256 "cd99fb2ce8889af801eac8cb3f7f35e58b3cea12dceead877db61658e4333722"
    end
  end

  def install
    bin.install "blessclient"
  end

  test do
    system "#{bin}/blessclient version"
  end
end
