# This file was generated by GoReleaser. DO NOT EDIT.
class BlessclientAT1 < Formula
  desc "SSH without pain."
  homepage "https://github.com/chanzuckerberg/blessclient"
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/chanzuckerberg/blessclient/releases/download/v1.0.1/blessclient_1.0.1_darwin_amd64.tar.gz"
    sha256 "98f9c3ce57c3a415060d410d5fe3189fe0b49bb1e1d15c27f7e0b5ca811ddcf7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/blessclient/releases/download/v1.0.1/blessclient_1.0.1_linux_amd64.tar.gz"
      sha256 "a4390696b1a64b61b4bd5848af93cbf9d090fa1c7073313cd49c178ad7b57c63"
    end
  end

  def install
    bin.install "blessclient"
  end

  test do
    system "#{bin}/blessclient version"
  end
end
