# This file was generated by GoReleaser. DO NOT EDIT.
class BlessclientAT1 < Formula
  desc "SSH without pain."
  homepage "https://github.com/chanzuckerberg/blessclient"
  version "1.1.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/chanzuckerberg/blessclient/releases/download/v1.1.4/blessclient_1.1.4_darwin_amd64.tar.gz"
    sha256 "d81b6d92d6e686076be2b790a80decbf07f94e4ef7162b80d24bc93c7dff69f8"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/blessclient/releases/download/v1.1.4/blessclient_1.1.4_linux_amd64.tar.gz"
      sha256 "8070449b138352e929b79fdfa722af99ddcab67079a873d4f795ee0edd30b084"
    end
  end

  def install
    bin.install "blessclient"
  end

  test do
    system "#{bin}/blessclient version"
  end
end
