# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Camelot < Formula
  desc "Publish the release."
  homepage "https://github.com/chanzuckerberg/camelot"
  version "0.7.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chanzuckerberg/camelot/releases/download/v0.7.0/camelot_0.7.0_darwin_arm64.tar.gz"
      sha256 "5ae5633e253f00bb61a405d25fe168388f61b5a4a4aee80373ff0400652ea277"

      def install
        bin.install "camelot"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/camelot/releases/download/v0.7.0/camelot_0.7.0_darwin_amd64.tar.gz"
      sha256 "f2aaf54264c59e5638c08a0aa857aa5eb852ba4269d4110ce63f6a37ab6c1bd1"

      def install
        bin.install "camelot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chanzuckerberg/camelot/releases/download/v0.7.0/camelot_0.7.0_linux_arm64.tar.gz"
      sha256 "71e32bed4ad7fcec19e98d1daf9b2a8ee52df04d69d95c3f3723dbefefa645e6"

      def install
        bin.install "camelot"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/camelot/releases/download/v0.7.0/camelot_0.7.0_linux_amd64.tar.gz"
      sha256 "5790438e70c0d9dcd2fac948f61769446bd52774a1f2cc3f0249105e559bafd9"

      def install
        bin.install "camelot"
      end
    end
  end

  test do
    system "#{bin}/camelot version"
  end
end
