# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Camelot < Formula
  desc "Publish the release."
  homepage "https://github.com/chanzuckerberg/camelot"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chanzuckerberg/camelot/releases/download/v0.6.0/camelot_0.6.0_darwin_arm64.tar.gz"
      sha256 "03d34f823165c235a7eab566fd42c1408f6a7cc50d14a3700916ffa621965f06"

      def install
        bin.install "camelot"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/camelot/releases/download/v0.6.0/camelot_0.6.0_darwin_amd64.tar.gz"
      sha256 "756471a93a42d2e30b0cb0bef683fa49104b1eee3da37f6d28e80324c2570773"

      def install
        bin.install "camelot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chanzuckerberg/camelot/releases/download/v0.6.0/camelot_0.6.0_linux_arm64.tar.gz"
      sha256 "084b3508027b21c8ceb12037043cd95a61643690001c0689e230a80b0fc14513"

      def install
        bin.install "camelot"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/camelot/releases/download/v0.6.0/camelot_0.6.0_linux_amd64.tar.gz"
      sha256 "b5d60a9f2ffbbaacff76b817ffc646b2ae8dbcc8bcbc69f9d3672a4a84dad2d5"

      def install
        bin.install "camelot"
      end
    end
  end

  test do
    system "#{bin}/camelot version"
  end
end
