# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CorePlatform < Formula
  desc "The command line tool for the Argus platform."
  homepage "https://github.com/chanzuckerberg/core-platform"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/core-platform/releases/download/v0.6.0/core-platform_0.6.0_darwin_amd64.tar.gz"
      sha256 "19a219020701a070846eef6300780ec499fcf3a31ffbecd46755de9a472e21c2"

      def install
        bin.install "argus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chanzuckerberg/core-platform/releases/download/v0.6.0/core-platform_0.6.0_darwin_arm64.tar.gz"
      sha256 "62b75fa621c3091a5a72b5bcd5280ed1f0fd5c721249017fbe30c52a66801233"

      def install
        bin.install "argus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/core-platform/releases/download/v0.6.0/core-platform_0.6.0_linux_amd64.tar.gz"
      sha256 "c999d273b349eb1dbd468b59fa40b374a1f52acd3c66ba8e8271a93b9f68dc64"

      def install
        bin.install "argus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chanzuckerberg/core-platform/releases/download/v0.6.0/core-platform_0.6.0_linux_arm64.tar.gz"
      sha256 "3647acecc2813d76fe9c9e0eb4fbf76f3b3a03971bba0ad9dd37051e8c5946cb"

      def install
        bin.install "argus"
      end
    end
  end

  test do
    system "#{bin}/argus"
  end
end
