# This file was generated by GoReleaser. DO NOT EDIT.
class CrcSquared < Formula
  desc "Light speed crc32c checksums"
  homepage "https://github.com/chanzuckerberg/crc-squared"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/chanzuckerberg/crc-squared/releases/download/v0.1.0/crc-squared_0.1.0_darwin_amd64.tar.gz"
    sha256 "8b3196f290eeff0bedc223b4ae1db1fe2ac532387ed3626517ee55f233e822d8"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/crc-squared/releases/download/v0.1.0/crc-squared_0.1.0_linux_amd64.tar.gz"
      sha256 "667f1adb4550ed8521305d2c2f66549c696e83bde2fd501d3d6abdd20e1f7957"
    end
  end

  def install
    bin.install "crc-squared"
    bash_completion.install "completions/bash" => "crc-squared"
    zsh_completion.install "completions/zsh" => "_crc-squared"
  end

  test do
    system "#{bin}/crc-squared --version"
  end
end
