# This file was generated by GoReleaser. DO NOT EDIT.
class CrcSquared < Formula
  desc "Light speed crc32c checksums"
  homepage "https://github.com/chanzuckerberg/crc-squared"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/chanzuckerberg/crc-squared/releases/download/v0.1.0/crc-squared_0.1.0_darwin_amd64.tar.gz"
    sha256 "046e1b9f9f7e5415f6d6c58a224bdd3cabd9ae0fc4f4141854fdc3306057c0a5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/crc-squared/releases/download/v0.1.0/crc-squared_0.1.0_linux_amd64.tar.gz"
      sha256 "0adbabef1e994f4e3f5203d623dc653bdcefb405ca56ef7a9aa786a076811d98"
    end
  end

  def install
    bin.install "crc-squared"
    bash_completion.install "completions/bash" => "crc-squared"
    zsh_completion.install "completions/zsh" => "_crc-squared"
  end

  test do
    system "#{bin}/crc-squared --version"
  end
end
