# This file was generated by GoReleaser. DO NOT EDIT.
class CrcSquared < Formula
  desc "Copy large files to, from, and between s3 buckets with parallelism"
  homepage "https://github.com/chanzuckerberg/crc-squared"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/chanzuckerberg/crc-squared/releases/download/v0.1.0/crc-squared_0.1.0_darwin_amd64.tar.gz"
    sha256 "de2630c531ca9995a16970430855bf57f3fd18f72c9573c7eddba8bcda6d50fc"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/crc-squared/releases/download/v0.1.0/crc-squared_0.1.0_linux_amd64.tar.gz"
      sha256 "90d468868e4e2f36c5aa6472d9b7aabf1606f4af5614bb4791eccc9e0802bc39"
    end
  end

  def install
    bin.install "crc-squared"
    bash_completion.install "completions/bash" => "crc-squared"
    zsh_completion.install "completions/zsh" => "_crc-squared"
  end

  test do
    system "#{bin}/crc-squared --version"
  end
end
