# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CzidCli < Formula
  desc "A CLI for uploading samples to Chan Zuckerberg ID"
  homepage "https://github.com/chanzuckerberg/czid-cli"
  version "4.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chanzuckerberg/czid-cli/releases/download/v4.1.1/czid-cli_darwin_arm64.tar.gz"
      sha256 "8c90016846fe14dab836426fef5f77052bd111fb6f74106fa3512d896294cae4"

      def install
        bin.install "czid"
        bash_completion.install "bash_completion" => "czid"
        zsh_completion.install "zsh_completion" => "_czid"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/czid-cli/releases/download/v4.1.1/czid-cli_darwin_amd64.tar.gz"
      sha256 "db664d556d8466a8edec04036aed7fe331ebaded58eda8839d93bcfe5af02849"

      def install
        bin.install "czid"
        bash_completion.install "bash_completion" => "czid"
        zsh_completion.install "zsh_completion" => "_czid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/czid-cli/releases/download/v4.1.1/czid-cli_linux_amd64.tar.gz"
      sha256 "f7d6b089578035cd88960ae8d67aff937c7f783b938f0f03299a817c00d8e531"

      def install
        bin.install "czid"
        bash_completion.install "bash_completion" => "czid"
        zsh_completion.install "zsh_completion" => "_czid"
      end
    end
  end

  test do
    system "#{bin}/czid --version"
  end
end
