# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CzidCli < Formula
  desc "A CLI for uploading samples to Chan Zuckerberg ID"
  homepage "https://github.com/chanzuckerberg/czid-cli"
  version "3.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chanzuckerberg/czid-cli/releases/download/v3.0.0/czid-cli_darwin_arm64.tar.gz"
      sha256 "05fba987316f6d3215b088fb976179db40e24aa2d7dc3ab5e478267ca3dfbe8f"

      def install
        bin.install "czid"
        bash_completion.install "bash_completion" => "czid"
        zsh_completion.install "zsh_completion" => "_czid"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/czid-cli/releases/download/v3.0.0/czid-cli_darwin_amd64.tar.gz"
      sha256 "5397d25e640f7d2899728b05be10fe148bd28b9b18a15631769686db69cd9c39"

      def install
        bin.install "czid"
        bash_completion.install "bash_completion" => "czid"
        zsh_completion.install "zsh_completion" => "_czid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/czid-cli/releases/download/v3.0.0/czid-cli_linux_amd64.tar.gz"
      sha256 "27fc3720d38c7e536a4abcf9271169dde55826d5e557e273b9549e6a9bfa16eb"

      def install
        bin.install "czid"
        bash_completion.install "bash_completion" => "czid"
        zsh_completion.install "zsh_completion" => "_czid"
      end
    end
  end

  test do
    system "#{bin}/czid --version"
  end
end
