# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CzidCli < Formula
  desc "A CLI for uploading samples to Chan Zuckerberg ID"
  homepage "https://github.com/chanzuckerberg/czid-cli"
  version "4.1.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chanzuckerberg/czid-cli/releases/download/v4.1.3/czid-cli_darwin_arm64.tar.gz"
      sha256 "5850c19ea1e60cd1bc6e5447956ee254828f51e48d95299b6041001634a4274c"

      def install
        bin.install "czid"
        bash_completion.install "bash_completion" => "czid"
        zsh_completion.install "zsh_completion" => "_czid"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/czid-cli/releases/download/v4.1.3/czid-cli_darwin_amd64.tar.gz"
      sha256 "44506a4fa4eb31e1736e034b63a786ac7117319ab7b4c39d153e2fc2cb74642d"

      def install
        bin.install "czid"
        bash_completion.install "bash_completion" => "czid"
        zsh_completion.install "zsh_completion" => "_czid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/czid-cli/releases/download/v4.1.3/czid-cli_linux_amd64.tar.gz"
      sha256 "3bcf159858247d3d9bd7ebb5461773daca36a68f2713c37ecfaee3c541fe60c8"

      def install
        bin.install "czid"
        bash_completion.install "bash_completion" => "czid"
        zsh_completion.install "zsh_completion" => "_czid"
      end
    end
  end

  test do
    system "#{bin}/czid --version"
  end
end
