# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DeltaShare < Formula
  desc "The command line tool for the CZI Databricks Delta Share short-lived tokens."
  homepage "https://github.com/chanzuckerberg/delta-share"
  version "0.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/delta-share/releases/download/v0.0.9/delta-share_0.0.9_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2f8aa9d75fa3fb4b791c23f1c03ee71e42b255a2a5aff555bb12388d2e9302fb"

      def install
        bin.install "delta-share"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chanzuckerberg/delta-share/releases/download/v0.0.9/delta-share_0.0.9_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f084aab1a57365f8c62c597b4ecb4ec304f6ef2a4b8b2694edcfe36a04ab35c5"

      def install
        bin.install "delta-share"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chanzuckerberg/delta-share/releases/download/v0.0.9/delta-share_0.0.9_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "d221f93ba628768d50ac1e98bd524f7f62de3715cd243f588f638168f56f719a"

        def install
          bin.install "delta-share"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chanzuckerberg/delta-share/releases/download/v0.0.9/delta-share_0.0.9_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "395378754a5a2ae8df7eed7681a6337aa811c099b17c0f572c09f7646f8a6639"

        def install
          bin.install "delta-share"
        end
      end
    end
  end

  test do
    system "#{bin}/delta-share version"
  end
end
