# This file was generated by GoReleaser. DO NOT EDIT.
class Fogg < Formula
  desc "Terraform without pain."
  homepage "https://github.com/chanzuckerberg/fogg"
  url "https://github.com/chanzuckerberg/fogg/releases/download/v0.24.1/fogg_0.24.1_darwin_amd64.tar.gz"
  version "0.24.1"
  sha256 "e5c20c2da3ad50a603bd89614d75af1d1752712d86e349857139c6bfe817c53c"

  def install
    bin.install "fogg"
  end

  test do
    system "#{bin}/fogg version"
  end
end
