# This file was generated by GoReleaser. DO NOT EDIT.
class Fogg < Formula
  desc "Terraform without pain."
  homepage "https://github.com/chanzuckerberg/fogg"
  version "0.47.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/chanzuckerberg/fogg/releases/download/v0.47.0/fogg_0.47.0_darwin_amd64.tar.gz"
    sha256 "d3b72376b7b78ed1fff4643d10954ea24bd1ed63c2a3b63615c7808b698223b3"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/fogg/releases/download/v0.47.0/fogg_0.47.0_linux_amd64.tar.gz"
      sha256 "ec2a639aff7cf3f42b8d9630cd2b0da82612e65f648e126cb5385b9abc8555a6"
    end
  end

  def install
    bin.install "fogg"
  end

  test do
    system "#{bin}/fogg version"
  end
end
