# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fogg < Formula
  desc "Terraform without pain."
  homepage "https://github.com/chanzuckerberg/fogg"
  version "0.89.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chanzuckerberg/fogg/releases/download/v0.89.0/fogg_0.89.0_darwin_arm64.tar.gz"
      sha256 "8684fa1dda170df4b27fd2197fc38aca95d57c76a9b226c60a3f589355f9ce1d"

      def install
        bin.install "fogg"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/fogg/releases/download/v0.89.0/fogg_0.89.0_darwin_amd64.tar.gz"
      sha256 "28b1c1fa96c7cb1f4964f3a00d3bf5e523e6d71ae1074d2b7016f52d19771468"

      def install
        bin.install "fogg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chanzuckerberg/fogg/releases/download/v0.89.0/fogg_0.89.0_linux_arm64.tar.gz"
      sha256 "f75aff75cb1584f536ec42acbb9638392e2b04c4091d2a9fefef9c74f0fc0bfa"

      def install
        bin.install "fogg"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/fogg/releases/download/v0.89.0/fogg_0.89.0_linux_amd64.tar.gz"
      sha256 "478889c1cf52b5e6a19099cdb6ab5f8f4767605388608feae7820d3d3e0c5322"

      def install
        bin.install "fogg"
      end
    end
  end

  test do
    system "#{bin}/fogg version"
  end
end
