# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Happy < Formula
  desc "A command line tool for happy path."
  homepage "https://github.com/chanzuckerberg/happy"
  version "0.104.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chanzuckerberg/happy/releases/download/v0.104.0/happy_0.104.0_darwin_arm64.tar.gz"
      sha256 "bab7d2663db59b3a12055f6311837e7861f9b625874a4f9af9a4bdc2aa4b364b"

      def install
        bin.install "happy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/happy/releases/download/v0.104.0/happy_0.104.0_darwin_amd64.tar.gz"
      sha256 "70128d385231fb553cfb8aff505feb30582fd3ee1715dbb6d331e4c3c190a273"

      def install
        bin.install "happy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chanzuckerberg/happy/releases/download/v0.104.0/happy_0.104.0_linux_arm64.tar.gz"
      sha256 "dcacc6f67a0ab45cb491d9a9595040662cb9bce7a5eaa602970e57452afdd1f1"

      def install
        bin.install "happy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/happy/releases/download/v0.104.0/happy_0.104.0_linux_amd64.tar.gz"
      sha256 "984255eea4ed2faa4bf1eb69ca16dbcadb77f3e3f3a3d9f7e62b1837ec5429ae"

      def install
        bin.install "happy"
      end
    end
  end

  test do
    system "#{bin}/happy"
  end
end
