# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HappyDeploy < Formula
  desc "A command line tool for happy path."
  homepage "https://github.com/chanzuckerberg/happy-deploy"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/happy-deploy/releases/download/v0.1.2/happy-deploy_0.1.2_darwin_amd64.tar.gz"
      sha256 "4015c7f1aa4c8aac5f0b38bc395abab4d886b57e3dca273986e17c6205fd02bd"

      def install
        bin.install "happy-deploy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chanzuckerberg/happy-deploy/releases/download/v0.1.2/happy-deploy_0.1.2_darwin_arm64.tar.gz"
      sha256 "1484155dafdb785788f9ff30ea85a9a43a96f388429e0283a0337e1d28b32481"

      def install
        bin.install "happy-deploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chanzuckerberg/happy-deploy/releases/download/v0.1.2/happy-deploy_0.1.2_linux_arm64.tar.gz"
      sha256 "fb0282916753028cba8bb939aaa1a6fd95c304db03290ad57ba11f375f2f86e7"

      def install
        bin.install "happy-deploy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/happy-deploy/releases/download/v0.1.2/happy-deploy_0.1.2_linux_amd64.tar.gz"
      sha256 "90d1a6e773617192e1cb34adc621f5e7237106b756a99173809a77f9dc47b8f0"

      def install
        bin.install "happy-deploy"
      end
    end
  end

  test do
    system "#{bin}/happy-deploy"
  end
end
