# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HappyRc < Formula
  desc "A command line tool for happy path."
  homepage "https://github.com/chanzuckerberg/happy"
  version "0.28.0-e992bb4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chanzuckerberg/happy/releases/download/v0.28.0-e992bb4/happy_0.28.0-e992bb4_darwin_arm64.tar.gz"
      sha256 "fb5568e6c65857d3d91c11f08a30049c78e6f5aa87801c17d64ec59b3467995e"

      def install
        bin.install "happy-rc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/happy/releases/download/v0.28.0-e992bb4/happy_0.28.0-e992bb4_darwin_amd64.tar.gz"
      sha256 "334bcefe778b451fafd904341bc5972e1e92e0a3a6616d6df64034b52b963e3d"

      def install
        bin.install "happy-rc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chanzuckerberg/happy/releases/download/v0.28.0-e992bb4/happy_0.28.0-e992bb4_linux_arm64.tar.gz"
      sha256 "6998c66c70b6c47b4dd514549b84adc65db46769f6d749a18886f703e22950fb"

      def install
        bin.install "happy-rc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/happy/releases/download/v0.28.0-e992bb4/happy_0.28.0-e992bb4_linux_amd64.tar.gz"
      sha256 "51e76310d96003ea8187e6c13727f26ce2250b0ace1d4a867650ff490e196724"

      def install
        bin.install "happy-rc"
      end
    end
  end

  test do
    system "#{bin}/happy-rc"
  end
end
