# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HappyRc < Formula
  desc "A command line tool for happy path."
  homepage "https://github.com/chanzuckerberg/happy"
  version "0.20.0-6ad8fa2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chanzuckerberg/happy/releases/download/v0.20.0-6ad8fa2/happy_0.20.0-6ad8fa2_darwin_arm64.tar.gz"
      sha256 "c05e00ee33a5378c4830ee9edef691d515f582052a0fe07c99a88dfa7890f393"

      def install
        bin.install "happy-rc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/happy/releases/download/v0.20.0-6ad8fa2/happy_0.20.0-6ad8fa2_darwin_amd64.tar.gz"
      sha256 "e4e8cd4618641abcb2613cbe5a9f5502d5069d0383236c6dadcd3e3e21affb4c"

      def install
        bin.install "happy-rc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chanzuckerberg/happy/releases/download/v0.20.0-6ad8fa2/happy_0.20.0-6ad8fa2_linux_arm64.tar.gz"
      sha256 "b983e78e4f4bebe4e97a795008f17902067b029edb9b14f4ba264113f4197a3e"

      def install
        bin.install "happy-rc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/happy/releases/download/v0.20.0-6ad8fa2/happy_0.20.0-6ad8fa2_linux_amd64.tar.gz"
      sha256 "344783704d51b0292b59a899af9ab8fe35021c169bd9dae78c09b0edaf5e039f"

      def install
        bin.install "happy-rc"
      end
    end
  end

  test do
    system "#{bin}/happy-rc"
  end
end
