# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hvm < Formula
  desc "An environment manager for happy path."
  homepage "https://github.com/chanzuckerberg/happy"
  version "0.120.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chanzuckerberg/happy/releases/download/v0.120.1/hvm_0.120.1_darwin_arm64.tar.gz"
      sha256 "adcf7191ebd45db74ee8af103b1ea9c4152f63ac287690f51d0ba872ae7432d8"

      def install
        bin.install "hvm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/happy/releases/download/v0.120.1/hvm_0.120.1_darwin_amd64.tar.gz"
      sha256 "e97028a27681f339c519a7e19c0403e8710d39eab2d8d2d804d631776428f038"

      def install
        bin.install "hvm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chanzuckerberg/happy/releases/download/v0.120.1/hvm_0.120.1_linux_arm64.tar.gz"
      sha256 "e69ad3d94a7527dc3c038ed42ac333760964c501cfaa27d109b5f917f117f6ae"

      def install
        bin.install "hvm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/happy/releases/download/v0.120.1/hvm_0.120.1_linux_amd64.tar.gz"
      sha256 "462e100274e54749f5dccc7004784403b027e314fa99f2b997d841dfb355cb93"

      def install
        bin.install "hvm"
      end
    end
  end

  test do
    system "#{bin}/hvm"
  end
end
