# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hvm < Formula
  desc "An environment manager for happy path."
  homepage "https://github.com/chanzuckerberg/happy"
  version "0.103.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chanzuckerberg/happy/releases/download/v0.103.0/hvm_0.103.0_darwin_arm64.tar.gz"
      sha256 "d5ab4b25bd508dc8b5691ed1af81a4ee994d2928f39e11d026be24ddafe95496"

      def install
        bin.install "hvm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/happy/releases/download/v0.103.0/hvm_0.103.0_darwin_amd64.tar.gz"
      sha256 "fe05c59cefdf1ecd8e15c8066aae103508eb2cd41314c6dac11ea66ac58bf0b0"

      def install
        bin.install "hvm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chanzuckerberg/happy/releases/download/v0.103.0/hvm_0.103.0_linux_arm64.tar.gz"
      sha256 "2bcd08a0376bbcac8e56cb71a8e4d53bd8403eeb0844799e0f4dea14e5bd007b"

      def install
        bin.install "hvm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/happy/releases/download/v0.103.0/hvm_0.103.0_linux_amd64.tar.gz"
      sha256 "5c5a42432360e9d263ab6e0b5b2bdcb02a72953e16ab554a2a56fd4a5fb6988f"

      def install
        bin.install "hvm"
      end
    end
  end

  test do
    system "#{bin}/hvm"
  end
end
