# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IdseqCliV2 < Formula
  desc "A CLI for uploading samples to IDSeq"
  homepage "https://github.com/chanzuckerberg/idseq-cli-v2"
  version "2.2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/idseq-cli-v2/releases/download/v2.2.0/idseq-cli-v2_darwin_amd64.tar.gz"
      sha256 "f835274b23b0a3df6f593ef208989dcf6ed85c5202bfb1f11bf738e3cfaba889"
    end
    if Hardware::CPU.arm?
      url "https://github.com/chanzuckerberg/idseq-cli-v2/releases/download/v2.2.0/idseq-cli-v2_darwin_arm64.tar.gz"
      sha256 "b6c50c1c73245d6b1ffda7d9fc2a5dbbd13df5ba108b1a024847e6c788981e20"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/idseq-cli-v2/releases/download/v2.2.0/idseq-cli-v2_linux_amd64.tar.gz"
      sha256 "0b1a6d17635ff2c556cbdf8d2530ae662712e2978e8b932ac977ef3405b066b0"
    end
  end

  def install
    bin.install "idseq"
    bash_completion.install "bash_completion" => "idseq"
    zsh_completion.install "zsh_completion" => "_idseq"
  end

  test do
    system "#{bin}/idseq --version"
  end
end
