# This file was generated by GoReleaser. DO NOT EDIT.
class Reaper < Formula
  desc "Don't fear."
  homepage "https://github.com/chanzuckerberg/reaper"
  url "https://github.com/chanzuckerberg/reaper/releases/download/v0.0.3/reaper_0.0.3_darwin_amd64.tar.gz"
  version "0.0.3"
  sha256 "80231c6e8ce7e67769b8a6ff54b1f91ce56ea308663a1e1eff1967d3b20a25de"

  def install
    bin.install "reaper"
  end

  test do
    system "#{bin}/reaper version"
  end
end
