# This file was generated by GoReleaser. DO NOT EDIT.
class Reaper < Formula
  desc "Don't fear."
  homepage "https://github.com/chanzuckerberg/reaper"
  url "https://github.com/chanzuckerberg/reaper/releases/download/v0.0.4/reaper_0.0.4_darwin_amd64.tar.gz"
  version "0.0.4"
  sha256 "500b69e8f60532d9d35b0d04c3ea45372bdd1d709de3eee101602d530d324574"

  def install
    bin.install "reaper"
  end

  test do
    system "#{bin}/reaper version"
  end
end
