# This file was generated by GoReleaser. DO NOT EDIT.
class Rotator < Formula
  desc "Rotating credentials."
  homepage "https://github.com/chanzuckerberg/rotator"
  version "0.0.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/chanzuckerberg/rotator/releases/download/v0.0.6/rotator_0.0.6_darwin_amd64.tar.gz"
    sha256 "ad81f3c9adfcb4bc75043d5a7b83432cc40e221b09f040c808527ba023955507"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/rotator/releases/download/v0.0.6/rotator_0.0.6_linux_amd64.tar.gz"
      sha256 "22bc6caaddc8c1c8aae6d8413393f5f9ed0a6e412b95bd82910e468fb9ef5ffb"
    end
  end

  def install
    bin.install "rotator"
  end

  test do
    system "#{bin}/rotator --help"
  end
end
