# This file was generated by GoReleaser. DO NOT EDIT.
class Rotator < Formula
  desc "Rotating credentials."
  homepage "https://github.com/chanzuckerberg/rotator"
  version "0.5.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/chanzuckerberg/rotator/releases/download/v0.5.1/rotator_0.5.1_darwin_amd64.tar.gz"
    sha256 "94cb0d98c44f0e7a0056d131e3b12ca08900b4bdb4de7049d5197aef36eb2cea"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/rotator/releases/download/v0.5.1/rotator_0.5.1_linux_amd64.tar.gz"
      sha256 "6e4e47a782e4f0aa8fec8964be2224fd308405b07aad98c6223d178f0ec958c8"
    end
  end

  def install
    bin.install "rotator"
  end

  test do
    system "#{bin}/rotator --help"
  end
end
