# This file was generated by GoReleaser. DO NOT EDIT.
class Rotator < Formula
  desc "Rotating credentials."
  homepage "https://github.com/chanzuckerberg/rotator"
  version "0.5.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/chanzuckerberg/rotator/releases/download/v0.5.5/rotator_0.5.5_darwin_amd64.tar.gz"
    sha256 "08b1956b3bbcbb42bb12b9b4431337dd0f3ff261944168a849f89bfbf3be2d72"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/rotator/releases/download/v0.5.5/rotator_0.5.5_linux_amd64.tar.gz"
      sha256 "4bb7ee43c37af638870703502ba72c3ad79897a7f594cf394f51f6360301e22b"
    end
  end

  def install
    bin.install "rotator"
  end

  test do
    system "#{bin}/rotator --help"
  end
end
