# This file was generated by GoReleaser. DO NOT EDIT.
class S3parcp < Formula
  desc "Copy large files to, from, and between s3 buckets with parallelism"
  homepage "https://github.com/chanzuckerberg/s3parcp"
  version "0.2.1-test-16"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/chanzuckerberg/s3parcp/releases/download/v0.2.1-test-16/s3parcp_0.2.1-test-16_Darwin_x86_64.tar.gz"
    sha256 "ffa05f9fa1d5c2e81eb1d35418c4ec31b1733cad5b935abaf3efc52eb814519c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/chanzuckerberg/s3parcp/releases/download/v0.2.1-test-16/s3parcp_0.2.1-test-16_Linux_x86_64.tar.gz"
      sha256 "3780b9f79e37b37367f27630526b72e5bd0eae1a4cf2444cee53bbfc9900ffef"
    end
  end

  def install
    bin.install "s3parcp" |
    bash_completion.install "completions/bash"
  end

  test do
    system "#{bin}/s3parcp --version"
  end
end
